import * as Yup from 'yup';

export const validationSchema = Yup.object().shape({
  departamento: Yup.string().nullable(),
  unidad: Yup.string().nullable(),
  tipoOrden: Yup.string().nullable(),
  nroOrden: Yup.string().nullable(),
  tipoOperativo: Yup.string().nullable(),
  tiempoOperativo: Yup.string().nullable(),
  nombreOperativo: Yup.string().nullable(),
  fechaInicio: Yup.date().nullable(),
  horaInicio: Yup.date().nullable(),
  horaFin: Yup.date().nullable(),
  fechaFin: Yup.date().nullable(),
  observacionesOrden: Yup.string().nullable(),
  seccional: Yup.array().of(Yup.string()),
  barrios: Yup.array().of(Yup.string()),
  moviles: Yup.number().min(0, 'El número de móviles no puede ser negativo').nullable(),
  ppssEnMovil: Yup.number().min(0, 'El número de PPSS en móvil no puede ser negativo').nullable(),
  ssoo: Yup.number().min(0, 'El número de SSOO no puede ser negativo').nullable(),
  motos: Yup.number().min(0, 'El número de motos no puede ser negativo').nullable(),
  motosBitripuladas: Yup.number().min(0, 'El número de motos bitripuladas no puede ser negativo').nullable(),
  hipos: Yup.number().min(0, 'El número de hipos no puede ser negativo').nullable(),
  canes: Yup.number().min(0, 'El número de canes no puede ser negativo').nullable(),
  pieTierra: Yup.number().min(0, 'El número de pie a tierra no puede ser negativo').nullable(),
  drones: Yup.number().min(0, 'El número de drones no puede ser negativo').nullable(),
  antidisturbioApostado: Yup.number().min(0, 'El número de antidisturbios apostados no puede ser negativo').nullable(),
  antidisturbioAlerta: Yup.number().min(0, 'El número de antidisturbios en alerta no puede ser negativo').nullable(),
  geoApostado: Yup.number().min(0, 'El número de GEO apostados no puede ser negativo').nullable(),
  geoAlerta: Yup.number().min(0, 'El número de GEO en alerta no puede ser negativo').nullable(),
  totalPpss: Yup.number().min(0, 'El total de PPSS no puede ser negativo').nullable()
});
