import * as Yup from 'yup';

export const validationSchema = Yup.object().shape({
  departamento: Yup.string().required('El departamento es requerido'),
  unidad: Yup.string().required('La unidad es requerida'),
  tipoOrden: Yup.string().required('El tipo de orden es requerido'),
  nroOrden: Yup.string().required('El número de orden es requerido'),
  tipoOperativo: Yup.string().required('El tipo de operativo es requerido'),
  tiempoOperativo: Yup.string().required('El tiempo operativo es requerido'),
  nombreOperativo: Yup.string().required('El nombre del operativo es requerido'),
  fechaInicio: Yup.date().nullable(),
  horaInicio: Yup.date().nullable(),
  horaFin: Yup.date().nullable(),
  fechaFin: Yup.date().nullable(),
  observacionesOrden: Yup.string(),
  seccional: Yup.array().of(Yup.string()),
  mapa: Yup.array().of(Yup.string()),
  puntosControl: Yup.array().of(Yup.string()),
  recorridos: Yup.array().of(Yup.string()),
  barrios: Yup.array().of(Yup.string()),
  moviles: Yup.number().min(0, 'El número de móviles no puede ser negativo'),
  ppssEnMovil: Yup.number().min(0, 'El número de PPSS en móvil no puede ser negativo'),
  ssoo: Yup.number().min(0, 'El número de SSOO no puede ser negativo'),
  motos: Yup.number().min(0, 'El número de motos no puede ser negativo'),
  motosBitripuladas: Yup.number().min(0, 'El número de motos bitripuladas no puede ser negativo'),
  hipos: Yup.number().min(0, 'El número de hipos no puede ser negativo'),
  canes: Yup.number().min(0, 'El número de canes no puede ser negativo'),
  pieTierra: Yup.number().min(0, 'El número de pie a tierra no puede ser negativo'),
  drones: Yup.number().min(0, 'El número de drones no puede ser negativo'),
  antidisturbioApostado: Yup.number().min(0, 'El número de antidisturbios apostados no puede ser negativo'),
  antidisturbioAlerta: Yup.number().min(0, 'El número de antidisturbios en alerta no puede ser negativo'),
  geoApostado: Yup.number().min(0, 'El número de GEO apostados no puede ser negativo'),
  geoAlerta: Yup.number().min(0, 'El número de GEO en alerta no puede ser negativo'),
  totalPpss: Yup.number().min(0, 'El total de PPSS no puede ser negativo')
});
