-- AlterTable
ALTER TABLE "tabla_principal" ALTER COLUMN "id" SET DEFAULT concat('REG', to_char(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS')),
ALTER COLUMN "moviles" SET DEFAULT 0,
ALTER COLUMN "ppssEnMovil" SET DEFAULT 0,
ALTER COLUMN "ssoo" SET DEFAULT 0,
ALTER COLUMN "motos" SET DEFAULT 0,
ALTER COLUMN "motosBitripuladas" SET DEFAULT 0,
ALTER COLUMN "hipos" SET DEFAULT 0,
ALTER COLUMN "canes" SET DEFAULT 0,
ALTER COLUMN "pieTierra" SET DEFAULT 0,
ALTER COLUMN "drones" SET DEFAULT 0,
ALTER COLUMN "antidisturbioApostado" SET DEFAULT 0,
ALTER COLUMN "antidisturbioAlerta" SET DEFAULT 0,
ALTER COLUMN "geoApostado" SET DEFAULT 0,
ALTER COLUMN "geoAlerta" SET DEFAULT 0,
ALTER COLUMN "totalPpss" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT concat('USR', to_char(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS'));
